- hosts: all
  gather_facts: yes

  roles:
    - { role: appearance , tags: appearance }
    - { role: enviroment, tags: env }
    - { role: vim, tags: vim }
    - { role: tools, tags: tools }
    - { role: i3wm, tags: i3 }
    - { role: shells, tags: shell }
