---
- name: register anaconda home
  set_fact:
      __ENV: "{{ __ENV | list + envAnaconda | list }}"
  tags:
    - env

- name: register java home
  set_fact:
      __ENV: "{{ __ENV | list + envJava | list }}"
  tags:
    - env

- name: register spark home
  set_fact:
      __ENV: "{{ __ENV | list + envSpark | list }}"
  tags:
    - env

- name: register scala home
  set_fact:
      __ENV: "{{ __ENV | list + envScala | list }}"
  tags:
    - env

- name: register maven home
  set_fact:
      __ENV: "{{ __ENV | list + envMaven | list }}"
  tags:
    - env
    - shell

- name: register sbt home
  set_fact:
      __ENV: "{{ __ENV | list + envSBT | list }}"
  tags:
    - env

- name: register sbt credentials
  set_fact:
      __ENV: "{{ __ENV | list + envSBT_CREDENTIALS | list }}"
  tags:
    - env

- name: register yarn home
  set_fact:
      __ENV: "{{ __ENV | list + envYARN | list }}"
  tags:
    - env

- name: register yarn global
  set_fact:
      __ENV: "{{ __ENV | list + envYARN_GLOBAL | list }}"
  tags:
    - env

- name: register node home
  set_fact:
      __ENV: "{{ __ENV | list + envNODE | list }}"
  tags:
    - env

# setting path & alias
- name: shells - add ansible manage block in .bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "######### {mark} Ansible Manages Blocks #########"
    block: "{{ lookup('template', './bash.j2') }}"
  tags:
    - env

- name: shells - add ansible manage block in fish.config
  blockinfile:
    path: ~/.config/fish/config.fish
    marker: "######### {mark} Ansible Manages Blocks #########"
    block: "{{ lookup('template', './fish.j2') }}"
  tags:
    - env
