---

# install
- name: shell - install packages
  apt:
    name:
    - bash
    - fish
  become: true

# change default shell
- name: shell - determine shell executable location
  command: which fish
  register: fish

- name: shell - change default shell
  user: name="{{ ansible_user }}" shell="{{ fish.stdout }}"
  become: yes

- name: shell - copy bin src folder
  copy:
    src: "{{role_path }}/files/fish/"
    dest: "~/.config/fish"

# dev enviroments
- name: shell - dev enviroments
  import_tasks: dev_enviroments.yml

# setting path & alias
- name: shells - add ansible manage block in .bashrc
  blockinfile:
    path: ~/.bashrc
    marker: "######### {mark} Ansible Manages Blocks #########"
    block: "{{ lookup('template', './bash.j2') }}"
  tags:
    - env

- name: shells - add ansible manage block in fish.config
  blockinfile:
    path: ~/.config/fish/config.fish
    marker: "######### {mark} Ansible Manages Blocks #########"
    block: "{{ lookup('template', './fish.j2') }}"
  tags:
    - env
